Worksheet 0


Task 1


In [ ]:
def convert_units():
  """
  Converts between different units of measurement.

  Returns:
    None
  """
  print("Choose conversation type:")
  print("1. Length (meters <-> feet)")
  print("2. Weight (kilograms <-> pounds)")
  print("3. Volume (liters <-> gallons)")

  try :
    choice = int(input("Enter 1, 2, or 3:"))

    if choice == 1:
      value = float(input("Enter value:"))
      unit = input("Enter unit (m/f):").lower()
      if unit == "m":
        print(f"{value} meters = {value * 3.28084} feet")
      elif unit == "f":
        print(f"{value} feet = {value / 3.28084} meters")
      else:
        print("Invalid unit")

    elif choice == 2:
      value = float(input("Enter value:"))
      unit = input("Enter unit (kg/lb):").lower()
      if unit == 'kg':
        print(f"{value} kilograms = {value * 2.20462} pounds")
      elif unit == 'lb':
        print(f"{value} pounds = {value / 2.20462} kilograms")
      else:
        print("Invalid unit")

    elif choice == 3:
      value = float(input("Enter value:"))
      unit = input("Enter unit (l/g):").lower()
      if unit == 'l':
        print(f"{value} liters = {value * 0.264172} gallons")
      elif unit == 'g':
        print(f"{value} gallons = {value / 0.264172} liters")
      else:
        print("Invalid unit")

    else:
      print("Invalid choice")

  except ValueError:
    print("Invalid input")

convert_units()




Choose conversation type:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Enter 1, 2, or 3:1
Enter value:45
Enter unit (m/f):m
45.0 meters = 147.6378 feet


Task 2


In [ ]:
def calulate():
  """
  Performs various mathmatical operations on a list of numbers.

  Returns:
     None:
  """
  try:
      numbers = list(map(float, input("Enter a list of numbers separated by spaces:").split()))
      if not numbers:
         raise ValueError("No numbers entered.")
      print("Choose operations:")
      print("1. Sum")
      print("2. Average")
      print("3. Maximum")
      print("4. Minimum")
      choice = int(input("Enter 1, 2, 3, or 4:"))

      if choice == 1:
        print("Sum:", sum(numbers))
      elif choice == 2:
        print("Average:", sum(numbers) / len(numbers))
      elif choice == 3:
        print("Maximum:", max(numbers))
      elif choice == 4:
        print("Minimum:", min(numbers))
      else:
        print("Invalid choice. Please enter 1, 2, 3, or 4.")

  except ValueError:
      print("Invalid input. Please enter a list of numbers separated by spaces.")

calulate()


Enter a list of numbers separated by spaces:2
Choose operations:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4:4
Minimum: 2.0


Task 3


In [ ]:
def extract_every_other(list):
    return lst[::2]

def get_sublist(lst, start, end):
    return lst[start:end+1]

def reverse_list(lst):
    return lst[::-1]

def remove_first_and_last(lst):
    return lst[1:-1]

def get_first_n(lst, n):
    return lst[n]

def get_last_n(lst, n):
    return lst[-n]
def reverse_skip(lst):
    return lst[-2::-2]

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("Every other element:", extract_every_other(lst))
print("Sublist:", get_sublist(lst, 2, 6))
print("Reversed list:", reverse_list(lst))
print("Removed first and last:", remove_first_and_last(lst))
print("First 3 elements:", get_first_n(lst, 3))
print("Last 3 elements:", get_last_n(lst, 3))
print("Reversed and skipped:", reverse_skip(lst))


Every other element: [1, 3, 5, 7, 9]
Sublist: [3, 4, 5, 6, 7]
Reversed list: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
Removed first and last: [2, 3, 4, 5, 6, 7, 8, 9]
First 3 elements: 4
Last 3 elements: 8
Reversed and skipped: [9, 7, 5, 3, 1]


Task 4


In [ ]:
def flatten(lst):
    return [item for Sublist in lst for item in (flatten(Sublist) if isinstance(Sublist, list)else [Sublist])]

def access_nested_element(lst, indices):
  for index in indices:
    lst = lst[index]
  return lst

def sum_nested(lst):
  return sum(flatten(lst))

def remove_element(lst, elem):
    return [item for item in lst if item != elem]

def find_max(lst):
  return max(flatten(lst))

def count_occurences(lst, elem):
  return flatten(lst).count(elem)

def count_occurences(lst, elem):
  return flatten(lst).count(elem)

def deep_flatten(lst):
  return flatten(lst)

def average_nested(lst):
    flat = flatten(lst)
    return sum(flat)/len(flat)

nested_lst = [[1,2], [3, [4,5]], 6]
print("Flattened list:", flatten(nested_lst))
print("Accessed element:", access_nested_element(nested_lst, [0,1]))
print("Sum of nested list:", sum_nested(nested_lst))
print("Removed element:", remove_element(nested_lst, 3))
print("Max element:", find_max(nested_lst))
print("Count of element:", count_occurences(nested_lst, 2))
print("Deep flattened list:", deep_flatten(nested_lst))
print("Average of nested list:", average_nested(nested_lst))

Flattened list: [1, 2, 3, 4, 5, 6]
Accessed element: 2
Sum of nested list: 21
Removed element: [[1, 2], [3, [4, 5]], 6]
Max element: 6
Count of element: 1
Deep flattened list: [1, 2, 3, 4, 5, 6]
Average of nested list: 3.5


**Numpy** **Exercises**

Task 1

In [ ]:
import numpy as np

#creating arrays
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_zeros = np.zeros((3,3))
arr_ones = np.ones((2,2))
arr_range = np.arange(1,10,2)
arr_linspace = np.linspace(0,1,5)

print("1D Array:")
print(arr_1d)
print("2D Array:")
print(arr_2d)
print("Zeros Array:")
print(arr_zeros)
print("Ones Array:")
print(arr_ones)
print("Range Array:")
print(arr_range)
print("Linspace Array:")
print(arr_linspace)

reshaped_arr = arr_1d.reshape(5,1)
print("Reshaped 1D Array:")
print(reshaped_arr)

print("Element at (0,1):", arr_2d[0,1])
print("First row:", arr_2d[0,:])
print("Second column:", arr_2d[:,1])


1D Array:
[1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1.]
 [1. 1.]]
Range Array:
[1 3 5 7 9]
Linspace Array:
[0.   0.25 0.5  0.75 1.  ]
Reshaped 1D Array:
[[1]
 [2]
 [3]
 [4]
 [5]]
Element at (0,1): 2
First row: [1 2 3]
Second column: [2 5]


Task 2

In [ ]:
#Arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

#universal functions
print("Exponential:", np.exp(a))
print("Square root:", np.sqrt(a))
print("Logarithm:", np.log(a))

#linear algebra operations
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("Dot product:", np.dot(matrix_a, matrix_b))
print("Inverse of A:", np.linalg.inv(matrix_a))
print("Determinant of matrix_a:", np.linalg.det(matrix_a))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Square root: [1.         1.41421356 1.73205081]
Logarithm: [0.         0.69314718 1.09861229]
Dot product: [[19 22]
 [43 50]]
Inverse of A: [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of matrix_a: -2.0000000000000004


Task 3

In [ ]:
# silcing in 1D array
arr = np.array([10, 20, 30, 40 ,50])
print("First three elements:", arr[:3])
print("Last two elements:", arr[-2:])
print("Every other element:", arr[::2])

#slicing in 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("First two rows:", arr_2d[:2,:])
print("Last column:", arr_2d[:,-1])
print("Submatrix:", arr_2d[1:,1:])

First three elements: [10 20 30]
Last two elements: [40 50]
Every other element: [10 30 50]
First two rows: [[1 2 3]
 [4 5 6]]
Last column: [3 6 9]
Submatrix: [[5 6]
 [8 9]]


Task 4


In [ ]:
#Broadcasting example
A = np.array([[1], [2], [3]])
B = np.array([4, 5, 6])
C = A + B
print("Broadcasted result:", C)

Broadcasted result: [[5 6 7]
 [6 7 8]
 [7 8 9]]


Task 5

In [ ]:
#handling index errors
arr = np.array([1, 2, 3])
try:
   print(arr[3])
except IndexError as e:
   print("Index out of range", e)

#handling shape errors
try:
   a = np.array([1, 2, 3])
   b = np.array([[4, 5], [6, 7]])
   print(a + b)
except ValueError as e:
   print("Shape mismatch:", e)

Index out of range index 3 is out of bounds for axis 0 with size 3
Shape mismatch: operands could not be broadcast together with shapes (3,) (2,2) 
